project:
  type: book

book:
  title: "IDR4000 Kvantitativ Metode og Statstikk"
  subtitle: "Mappeeksamen"
  repo-url: https://github.com/ssiverts/IDR4000-eksamen.git
  note: "9406 ord"
  author: "406; Tal ord: 5104"
  date: "11/16/2023"
  chapters:
    - index.qmd
    - kapittel/01-reliabilitet.qmd
    - kapittel/02-labrapport.qmd
    - kapittel/03-vitenskapsfilosofi.qmd
    - kapittel/04-studiedesign.qmd
    - kapittel/05-analyse-av-repeterte-forsøk.qmd
    - references.qmd

bibliography: kapittel/references.bib
csl: resources/vancouver.csl

crossref:
  fig-title: "**Figur**"
  tbl-title: "**Tabell**"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



