project:
  type: book

book:
  title: "IDR4000 Mappeeksamen"
  author: "Kandidatnr"
  date: "11/17/2023"
  chapters:
    - index.qmd
    - kapittel/01-reliabilitet.qmd
    - kapittel/02-labrapport.qmd
    - kapittel/03-vitenskapsfilosofi.qmd
    - kapittel/04-studiedesign.qmd
    - kapittel/05-analyse-av-repeterte-forsøk.qmd

bibliography: kapittel/references.bib
csl: resources/vancouver.csl

crossref:
  fig-title: "**Figur**"
  tbl-title: "**Tabell**"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



